/****** TOW WITH VEHICLE / REMORQUER AVEC VEHICULE ******/

/**
 * List of class names of (ground or air) vehicles which can tow towables objects.
 * Liste des noms de classes des v�hicules terrestres pouvant remorquer des objets remorquables.
 */
R3F_LOG_CFG_remorqueurs = [
	"O_Quadbike_01_F",
    "B_Quadbike_01_F",
	"I_Quadbike_01_F",
	"C_Quadbike_01_F",
	"C_Offroad_01_F",
	"B_Truck_01_transport_F",
	"B_Truck_01_covered_F",
	"O_Truck_02_transport_F",
	"O_Truck_02_covered_F",
	"O_MRAP_02_hmg_F",
    "B_MRAP_01_F",
    "B_MRAP_01_gmg_F",
    "B_MRAP_01_hmg_F",
    "O_MRAP_02_F",
    "O_MRAP_02_gmg_F",
	"B_Boat_Transport_01_F",
	"O_Boat_Transport_01_F",
	"I_Boat_Transport_01_F",
	"B_Boat_Armed_01_minigun_F",
	"B_Lifeboat",	
	"O_Lifeboat",
	"C_Rubberboat",
	"O_Boat_Armed_01_hmg_F",
	"I_Boat_Armed_01_minigun_F",
	"B_APC_Wheeled_01_cannon_F",
	"O_APC_Wheeled_02_rcws_F",
	"I_MRAP_03_gmg_F",
	"I_MRAP_03_hmg_F",
	"I_MRAP_03_F",
	"B_SDV_01_F",
	"O_SDV_01_F",
	"B_APC_Tracked_01_rcws_F",
	"O_APC_Tracked_02_cannon_F"
];

/**
 * List of class names of towables objects.
 * Liste des noms de classes des objets remorquables.
 */
R3F_LOG_CFG_objets_remorquables = [
	"O_Quadbike_01_F",
    "B_Quadbike_01_F",
	"I_Quadbike_01_F",
	"C_Quadbike_01_F",
	"C_Offroad_01_F",
	"B_Truck_01_transport_F",
	"B_Truck_01_covered_F",
	"O_Truck_02_transport_F",
	"O_Truck_02_covered_F",
	"O_MRAP_02_hmg_F",
	"B_MRAP_01_F",
	"B_MRAP_01_gmg_F",
	"B_MRAP_01_hmg_F",
	"O_MRAP_02_F",
	"O_MRAP_02_gmg_F",
	"I_MRAP_03_F",
	"I_MRAP_03_hmg_F",
	"I_MRAP_03_gmg_F",
	"B_APC_Wheeled_01_cannon_F",
	"O_APC_Wheeled_02_rcws_F",
	"Land_Cargo20_Military_F",
	"Land_Cargo20_military_F",
	"Land_Cargo_Patrol_V1_F",
	"Land_MetalBarrel_F",
	"Land_HBarrierBig_F",
	"Land_Mil_WallBig_4m_F",
	"Land_HBarrier_3_F",
	"Land_HBarrier_5_F",
	"Land_HBarrier_1_F",
	"B_Boat_Transport_01_F",
	"O_Boat_Transport_01_F",
	"B_Boat_Armed_01_minigun_F",
	"B_Lifeboat",	
	"O_Lifeboat",
	"C_Rubberboat",
	"O_Boat_Armed_01_hmg_F",
	"B_SDV_01_F",
	"O_SDV_01_F"
];

/****** LIFT WITH VEHICLE / HELIPORTER AVEC VEHICULE ******/

/**
 * List of class names of air vehicles which can lift liftables objects.
 * Liste des noms de classes des v�hicules a�riens pouvant h�liporter des objets h�liportables.
 */
R3F_LOG_CFG_heliporteurs = [
	"B_Heli_Light_01_F",
	"B_Heli_Light_01_armed_F",
	"B_Heli_Attack_01_F",
	"B_Heli_Transport_01_F",
	"O_Heli_Attack_02_F",
	"O_Heli_Attack_02_black_F",
	"O_Heli_Light_02_F",
	"O_Heli_Light_02_unarmed_F",
	"I_Heli_Transport_02_F"
];

/**
 * List of class names of liftables objects.
 * Liste des noms de classes des objets h�liportables.
 */
R3F_LOG_CFG_objets_heliportables = [
	"O_Quadbike_01_F",
    "B_Quadbike_01_F",
	"I_Quadbike_01_F",
	"C_Quadbike_01_F",
	"C_Offroad_01_F",
	"B_Truck_01_transport_F",
	"B_Truck_01_covered_F",
	"O_Truck_02_transport_F",
	"O_Truck_02_covered_F",
    "B_MRAP_01_F",
    "B_MRAP_01_gmg_F",
    "B_MRAP_01_hmg_F",
    "O_MRAP_02_F",
	"O_MRAP_02_hmg_F",
    "O_MRAP_02_gmg_F",
    "I_MRAP_03_F",
    "I_MRAP_03_hmg_F",
    "I_MRAP_03_gmg_F",
	"B_APC_Wheeled_01_cannon_F",
	"O_APC_Wheeled_02_rcws_F",
	"B_Lifeboat",
	"O_Lifeboat",
	"C_Rubberboat",
	"B_Boat_Transport_01_F",
	"O_Boat_Transport_01_F",
	"I_Boat_Transport_01_F",
	"B_Boat_Armed_01_minigun_F",
	"O_Boat_Armed_01_hmg_F",
	"I_Boat_Armed_01_minigun_F",
	"B_SDV_01_F",
	"O_SDV_01_F",
	"B_Heli_Light_01_F",
	"B_Heli_Light_01_armed_F",
	"O_Heli_Light_02_unarmed_F",
	"I_Heli_Transport_02_F",
	"B_Heli_Transport_01_F",
	"O_Heli_Light_02_F",
	"B_Heli_Attack_01_F",
	"O_Heli_Attack_02_F",
	"O_Heli_Attack_02_black_F",
	"Land_Cargo20_Military_F",
	"Land_Cargo_Patrol_V1_F",
	"Land_MetalBarrel_F",
	"Land_HBarrierBig_F",
	"Land_Mil_WallBig_4m_F",
	"Land_HBarrier_3_F",
	"Land_HBarrier_5_F",
	"Land_HBarrier_1_F",
	"B_APC_Tracked_01_rcws_F",
	"O_APC_Tracked_02_cannon_F"
];


/****** LOAD IN VEHICLE / CHARGER DANS LE VEHICULE ******/


R3F_LOG_CFG_transporteurs = [
	// Unarmed vehicles
	["O_Quadbike_01_F", 50],
    ["B_Quadbike_01_F", 50],
	["I_Quadbike_01_F", 50],
	["C_Quadbike_01_F", 50],
	["C_Offroad_01_F", 50],
	["B_Truck_01_transport_F",100],
	["B_Truck_01_covered_F",100],
	["O_Truck_02_transport_F",100],
	["O_Truck_02_covered_F",100],
	// Light armor
	["O_MRAP_02_F", 40],
	["O_MRAP_02_gmg_F", 20],
	["O_MRAP_02_hmg_F", 20],
	["B_MRAP_01_F", 40],
	["B_MRAP_01_gmg_F", 20],
	["B_MRAP_01_hmg_F", 20],
	["I_MRAP_03_F", 40],
	["I_MRAP_03_hmg_F", 20],
	["I_MRAP_03_gmg_F", 20],
	// APC
	["B_APC_Wheeled_01_cannon_F",30],
	["O_APC_Wheeled_02_rcws_F",30],
	// Helis
	["B_Heli_Light_01_F", 30],
	["B_Heli_Light_01_armed_F", 30],
	["B_Heli_Attack_01_F", 10],
	["B_Heli_Transport_01_F", 80],
	["O_Heli_Attack_02_F", 30],
	["O_Heli_Attack_02_black_F", 50],
	["O_Heli_Light_02_F", 30],
	["O_Heli_Light_02_unarmed_F", 50],
	["I_Heli_Transport_02_F", 90],
	// Boats
	["B_Boat_Transport_01_F",15],
	["O_Boat_Transport_01_F",15],
	["I_Boat_Transport_01_F",15],
	["B_Lifeboat", 5],
	["O_Lifeboat", 5],
	["C_Rubberboat", 5],
	["B_Boat_Armed_01_minigun_F",5],
	["O_Boat_Armed_01_hmg_F",5],
	["I_Boat_Armed_01_minigun_F",5],
	["B_APC_Tracked_01_rcws_F", 40],
	["O_APC_Tracked_02_cannon_F", 40],
	["B_SDV_01_F",5],
	["O_SDV_01_F",5]
];

 
R3F_LOG_CFG_objets_transportables =  [
	["Box_NATO_Ammo_F",5],
	["Box_NATO_Grenades_F",5],
	["Box_NATO_AmmoOrd_F",5],
	["Box_IND_Ammo_F",5],
	["Box_IND_Grenades_F",5],
	["Box_IND_AmmoOrd_F",5],
	["Box_EAST_Ammo_F",5],
	["Box_EAST_Grenades_F",5],
	["Box_EAST_AmmoOrd_F",5],
	["Box_NATO_Wps_F",5],
	["Box_NATO_WpsLaunch_F",5],
	["Box_NATO_WpsSpecial_F",5],
	["B_supplyCrate_F",5],
	["Box_NATO_Support_F",5],
	["Box_IND_Wps_F",5],
	["Box_IND_WpsLaunch_F",5],
	["Box_IND_WpsSpecial_F",5],
	["I_supplyCrate_F",5],
	["Box_IND_Support_F",5],
	["Box_EAST_Wps_F",5],
	["Box_EAST_WpsLaunch_F",5],
	["Box_EAST_WpsSpecial_F",5],
	["O_supplyCrate_F",5],
	["Box_EAST_Support_F",5],
	["Land_CanisterPlastic_F", 1],
	["Land_Sacks_goods_F", 2],
	["Land_MetalBarrel_F", 2],
	["Land_HBarrierBig_F", 5],
	["Land_Mil_WallBig_4m_F",5],
	["Land_HBarrier_3_F", 3],
    ["Land_HBarrier_5_F", 5],
    ["Land_HBarrier_1_F", 1],
    ["Land_ToiletBox_F", 6],
	["Land_LampShabby_F",3],
	["O_Quadbike_01_F",10],
    ["B_Quadbike_01_F",10],
	["I_Quadbike_01_F",10],
	["C_Quadbike_01_F",10],
	["Land_ToiletBox_F", 5],
	["O_Lifeboat", 15],
	["B_Lifeboat", 15],
	["C_Rubberboat", 15],
	["B_SDV_01_F",5],
	["O_SDV_01_F",5],
	["O_Mortar_01_F", 15],
	["B_Mortar_01_F", 15],
	["Land_Sack_F", 1],
	["Land_Tyres_F", 3],
	["Land_Coil_F", 5],
	["Land_Pipes_Large_F", 5],
	["Land_Cargo_Patrol_V1_F", 30],
	["Land_Cargo20_Military_F", 30],
	["Land_Stone_8m_F", 5]
];

/****** MOVABLE-BY-PLAYER OBJECTS / OBJETS DEPLACABLES PAR LE JOUEUR ******/

R3F_LOG_CFG_objets_deplacables = [
	"Box_NATO_Ammo_F",
	"Box_NATO_Grenades_F",
	"Box_NATO_AmmoOrd_F",
	"Box_IND_Ammo_F",
	"Box_IND_Grenades_F",
	"Box_IND_AmmoOrd_F",
	"Box_EAST_Ammo_F",
	"Box_EAST_Grenades_F",
	"Box_EAST_AmmoOrd_F",
	"Box_NATO_Wps_F",
	"Box_NATO_WpsLaunch_F",
	"Box_NATO_WpsSpecial_F",
	"B_supplyCrate_F",
	"Box_NATO_Support_F",
	"Box_IND_Wps_F",
	"Box_IND_WpsLaunch_F",
	"Box_IND_WpsSpecial_F",
	"I_supplyCrate_F",
	"Box_IND_Support_F",
	"Box_EAST_Wps_F",
	"Box_EAST_WpsLaunch_F",
	"Box_EAST_WpsSpecial_F",
	"O_supplyCrate_F",
	"Box_EAST_Support_F",
	"Land_CanisterPlastic_F",
	"Land_Sacks_goods_F",
	"Land_MetalBarrel_F",
	"Land_HBarrierBig_F",
	"Land_HBarrier_1_F",
	"Land_HBarrier_3_F",
    "Land_HBarrier_5_F",
	"Land_Pipes_Large_F",
	"Land_CargoBox_V1_F",
    "Land_ToiletBox_F",
    "Land_LampDecor_F",
    "Land_Stone_8m_F",
	"Land_LampShabby_F",
	"Land_Mil_WallBig_4m_F",
	"O_Quadbike_01_F",
    "B_Quadbike_01_F",
	"I_Quadbike_01_F",
	"C_Quadbike_01_F",
	"Land_ToiletBox_F",
	"B_Boat_Transport_01_F",
	"B_Lifeboat",	
	"O_Lifeboat",
    "C_Rubberboat",
	"O_Boat_Transport_01_F",
	"I_Boat_Transport_01_F",
	"Land_Sack_F",
	"Land_Coil_F",
	"Land_Pipes_Large_F",
	"Land_Cargo_Patrol_V1_F",
	"Land_Cargo20_Military_F"
];
